/*
 * Copyright (c) 2017 Google LLC.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _ATMEL_SAMD_SOC_PINMAP_H_
#define _ATMEL_SAMD_SOC_PINMAP_H_

/* SERCOM in UART mode */

/* SPI SERCOM0 on MISO=PA08 MOSI=PA10 SCK=PA11 */
#define PIN_SPI_SAM0_SERCOM0_MISO {0, 8, PORT_PMUX_PMUXE_C_Val}
#define PIN_SPI_SAM0_SERCOM0_MOSI {0, 10, PORT_PMUX_PMUXE_C_Val}
#define PIN_SPI_SAM0_SERCOM0_SCK {0, 11, PORT_PMUX_PMUXE_C_Val}

/* SPI SERCOM1 on MISO=PA16 MOSI=PA18 SCK=PA19 */
#define PIN_SPI_SAM0_SERCOM1_MISO {0, 16, PORT_PMUX_PMUXE_C_Val}
#define PIN_SPI_SAM0_SERCOM1_MOSI {0, 18, PORT_PMUX_PMUXE_C_Val}
#define PIN_SPI_SAM0_SERCOM1_SCK {0, 19, PORT_PMUX_PMUXE_C_Val}

/* SPI SERCOM2 on MISO=PA12 MOSI=PA14 SCK=PA15 */
#define PIN_SPI_SAM0_SERCOM2_MISO {0, 12, PORT_PMUX_PMUXE_C_Val}
#define PIN_SPI_SAM0_SERCOM2_MOSI {0, 14, PORT_PMUX_PMUXE_C_Val}
#define PIN_SPI_SAM0_SERCOM2_SCK {0, 15, PORT_PMUX_PMUXE_C_Val}

/* SPI SERCOM3 on MISO=PA22 MOSI=PA20 SCK=PA21 */
#define PIN_SPI_SAM0_SERCOM3_MISO {0, 22, PORT_PMUX_PMUXE_D_Val}
#define PIN_SPI_SAM0_SERCOM3_MOSI {0, 20, PORT_PMUX_PMUXE_D_Val}
#define PIN_SPI_SAM0_SERCOM3_SCK {0, 21, PORT_PMUX_PMUXE_C_Val}

/* SPI SERCOM4 on MISO=PB12, MOSI=PB10, SCK=PB11 */
#define PIN_SPI_SAM0_SERCOM4_MISO {1, 12, PORT_PMUX_PMUXE_C_Val}
#define PIN_SPI_SAM0_SERCOM4_MOSI {1, 10, PORT_PMUX_PMUXE_D_Val}
#define PIN_SPI_SAM0_SERCOM4_SCK {1, 11, PORT_PMUX_PMUXE_D_Val}

/* SPI SERCOM5 on MISO=PB16 MOSI=PB22 SCK=PB23 */
#define PIN_SPI_SAM0_SERCOM5_MISO {1, 16, PORT_PMUX_PMUXE_C_Val}
#define PIN_SPI_SAM0_SERCOM5_MOSI {1, 22, PORT_PMUX_PMUXE_D_Val}
#define PIN_SPI_SAM0_SERCOM5_SCK {1, 23, PORT_PMUX_PMUXE_D_Val}

#endif /* _ATMEL_SAMD_SOC_PINMAP_H_ */
