# Makefile - Atmel SAM MCU family
#
# Copyright (c) 2016 Piotr Mienkowski
# SPDX-License-Identifier: Apache-2.0
#

obj-y += $(SOC_SERIES)/
obj-$(CONFIG_SOC_SERIES_SAM3X) += common/
obj-$(CONFIG_SOC_SERIES_SAM4S) += common/
obj-$(CONFIG_SOC_SERIES_SAME70) += common/
